
#' Draw type probabilities
#'
#' Draws probability of vector of causal types given a single realization of parameters, possibly drawn from model priors.
#'
#' @param model A model object generated by \code{make_model()}.
#' @param P A matrix. Parameter matrix. Not required but may be provided to avoid repeated computation for simulations.
#' @param parameters A numeric vector. Optionally specify parameters. By default, parameters is drawn from `using` argument (either from priors, posteriors, or from model$parameters)
#' @param using A string taking value "priors", "posteriors" or "parameters".
#' @export
#' @examples
#' draw_type_prob(model = make_model("X->Y"))
#'
draw_type_prob <- function(model,
                           P = NULL,
                           parameters = NULL,
                           using = NULL ){
  
  if(!is.null(parameters) & !is.null(using)) if(using!="parameters")
    stop("Parameters provided but using is not set to parameters")
  if(!is.null(parameters)) using <- "parameters"
  if(is.null(using)) {using <- "priors"; message("using not provided, priors assumed")}
  if(is.null(parameters))  parameters <- draw_parameters(model, using = using)
  if(is.null(P)) 	    P      <- get_parameter_matrix(model)
  
  # Type probabilities
  P.lambdas     <- P*parameters +	1 - P
  apply(P.lambdas, 2, prod)
  
}

#' Draw matrix of type probabilities, before or after estimation
#'
#' @param model A model, normally containing a prior or a posterior distribution.
#' @param using A character string indicating whether to use "priors", "posteriors" or "parameters".
#' @param parameters A numeric vector. True parameters to be used instead of parameters attached to the model in case `using` specifies `parameters`.
#' @param n_draws An integer. If no prior distribution is provided, generate prior distribution with \code{n_draws} number of draws.
#' @return A matrix of type probabilities.
#' @export
#' @examples
#' model <- make_model("X -> Y")
#' draw_type_prob_multiple(model, using = "priors", n_draws = 3)
#' draw_type_prob_multiple(model, using = "parameters", n_draws = 3)

draw_type_prob_multiple <- function(model,
                                    parameters = NULL,
                                    n_draws = 4000,
                                    using = "priors"){
  
  if(using == "parameters") {
    if(is.null(model$parameters) & is.null(parameters)) stop("please provide parameters")
    if(is.null(parameters)) parameters <- model$parameters
    return(draw_type_prob(model, parameters = parameters, using = using))
  }
  
  if(using == "priors"){
    if(is.null(model$prior_distribution)) {
      message("Prior distribution added to model")
      model <- set_prior_distribution(model, n_draws = n_draws)
    }
    param_dist <- model$prior_distribution
  }
  
  if(using == "posteriors"){
    if(is.null(model$posterior_distribution)) {
      stop("Model does not contain a posterior distribution")}
    param_dist <- rstan::extract(model$posterior, pars= "lambdas")$lambdas
  }
  
  apply(param_dist, 1, function(j) draw_type_prob(model, parameters = j))
}

