#' Draw parameters
#' Default behavior takes a random draw of parameters from priors; can also draw from posteriors, or return pre-defined parameters.
#'
#' @param model A model object generated by \code{make_model()}.
#' @param using String indicating whether to use `priors`, `posteriors` or `parameters`
#' @importFrom gtools rdirichlet
#' @importFrom rstan extract
#' @importFrom gtools rdirichlet
#' @return A named list of parameters.
#' @export
#' @examples
#' draw_parameters(model = make_model("X->Y"))
#'
draw_parameters <- function(model, using = NULL){

  if(is.null(using)) using <- "priors"

  if(!(using %in% c("priors", "posteriors", "parameters"))) stop(
    "`using` should be one of `priors`, `posteriors`, or `parameters`")

  if(using == "parameters")  parameters <- model$parameters_df$parameters

  if(using == "posteriors") {if(is.null(model$posterior)) stop("No posterior provided")
    param_dist <- extract(model$posterior, pars= "lambdas")$lambdas
    parameters <- param_dist[sample(nrow(param_dist),1),]}

  if(using == "priors") {
    priors     <- model$parameters_df$priors
    param_sets <- unique(model$parameters_df$param_set)

    parameters <- unlist(sapply(unique(param_sets), function(v){
      rdirichlet(1, priors[model$parameters_df$param_set == v])}))}

  # Clean up for export
  names(parameters) <- model$parameters_df$param_names

  parameters

}
