#' Draw event probabilities
#'
# `draw_event_prob` draws event probability vector `w`  given a single realization of parameters
#'
#' @param model A model object generated by \code{make_model()}.
#' @param P A matrix. Parameter matrix. Not required but may be provided to avoid repeated computation for simulations.
#' @param A A matrix. Ambiguity matrix. Not required but may be provided to avoid repeated computation for simulations.
#' @param parameters A numeric vector. Values of parameters may be specified. By default, parameters is drawn from priors.
#' @param type_prob A numeric vector. Type probabilities (usually not required).
#' @param using String indicating whether to use "priors", "posteriors" or "parameters".
#'
#' @export
#' @examples
#' model <- make_model("X -> Y")
#' draw_event_prob(model = model)
#' draw_event_prob(model = model, using = "parameters")
draw_event_prob <- function(model,
                            P = NULL,
                            A = NULL,
                            parameters = NULL,
                            type_prob = NULL,
                            using = NULL){


  if(is.null(parameters)) {parameters <- draw_parameters(model, using = using)}

  # Ambiguity matrix
  if(is.null(A)) 	    A <- get_ambiguities_matrix(model)

  # Type probabilities
  if(is.null(type_prob)) {
    type_prob <- draw_type_prob(model = model, P = P, parameters = parameters, using = using)}

  # Event probabilities  ## FLAG this is a hack for cases with only one possible data type
  if(ncol(A)==1) {out <- matrix(1); rownames(out) <- colnames(A); return(out)}

  out <- t(A) %*% type_prob
  colnames(out) <- "event_prob"
  return(out)

}
