#' Draw compact data
#'
#  Draw \code{n} events given event probabilities. Draws full data only. For incomplete data see `data_strategy`.
#'
#' @param model A model object generated by \code{make_model()}.
#' @param n An integer. Number of observations.
#' @param w A numeric vector of event probabilities.
#' @param P Parameter matrix. (Optional). May be provided to avoid repeated computation for simulations.
#' @param A Ambiguity matrix. (Optional). May be provided to avoid repeated computation for simulations.
#' @param parameters A numeric vector. Values of parameters may be specified. By default, it is drawn from priors.
#' @param using String indicating whether to use "priors", "posteriors" or "parameters".
#' @return A data frame of events
#' @importFrom stats rmultinom
#' @export
#'
#' @examples
#' model <- make_model("X -> Y")
#' draw_data_events(model = model)
draw_data_events <- function(model, n = 1,
                             w = NULL,
                             P = NULL,
                             A = NULL,
                             parameters = NULL,
                             using = NULL
){

  if(is.null(w)){
    if(is.null(P)) 	P <- get_parameter_matrix(model)
    if(is.null(A)) 	A <- get_ambiguities_matrix(model)
    w <- draw_event_prob(model, P, A, parameters = parameters, using = using)
  }

  # Draw events (Compact dataframe)
  data.frame(event = rownames(w), count = rmultinom(1, n, w))

}

