#' Draw event probabilities
#'
# `draw_event_prob` draws event probability vector `w`  given a single realization of parameters
#'
#' @param model A model object generated by \code{make_model()}.
#' @param P A matrix. Parameter matrix. Not required but may be provided to avoid repeated computation for simulations.
#' @param A A matrix. Ambiguity matrix. Not required but may be provided to avoid repeated computation for simulations.
#' @param parameters A numeric vector. Values of parameters may be specified. By default, parameters is drawn from priors.
#' @param type_prob A numeric vector. Type probabilities (usually not required).
#' @param using String indicating whether to use "priors", "posteriors" or "parameters".
#'
#' @export
#' @examples
#' model <- make_model("X -> Y", add_parameters = FALSE)
#' draw_event_prob(model = model)
#' draw_event_prob(model = model, parameters = rep(1, 6))
#' draw_event_prob(model = model, using = "priors")
#' model <- make_model("X -> Y", add_parameters = TRUE)
#' draw_event_prob(model = model, using = "parameters")
draw_event_prob <- function(model,
                            P = NULL,
                            A = NULL,
                            parameters = NULL,
                            type_prob = NULL,
                            using = NULL){

  # draw_event uses a parameter vector that is either provided directly or else drawn from priors or posteriors
  # a directly provided parameter vector is used instead of parameters contained in the model
  # if parameters is NULL but using  parameters is specified then model$parameters is used if available
  if(is.null(parameters)) if(!is.null(using)) if(using =="parameters") {
        if(is.null(model$parameters)) stop("No parameters provided")
        parameters <- model$parameters}

  if(is.null(parameters)) parameters <- draw_parameters(model, using = using)


  parameters <- check_params(parameters, get_param_set_names(model), warning = TRUE, model = model)

  # Ambiguity matrix
  # if(is.null(A)) 	    model <- set_ambiguities_matrix(model)
  A <- get_ambiguities_matrix(model)

  # Type probabilities
  if(is.null(type_prob)) {
    type_prob <- draw_type_prob(model = model, P = P, parameters = parameters, using = using)}

  # Event probabilities  ## FLAG this is a hack for cases with only one possible data type
  if(ncol(A)==1) {out <- matrix(1); rownames(out) <- colnames(A); return(out)}

  out <- t(A) %*% type_prob

  if(!isTRUE(all.equal(sum(out), 1))) warning("Event probabilities not summing to 1")
  colnames(out) <- "event_prob"
  return(out)

}
