#' Draw parameters
#' Default behavior takes a random draw of parameters from priors; can also draw from posteriors, or return pre-defined parameters.
#'
#' @param model A model object generated by \code{make_model()}.
#' @param using String indicating whether to use `priors`, `posteriors` or `parameters`
#' @importFrom gtools rdirichlet
#' @importFrom rstan extract
#' @importFrom gtools rdirichlet
#' @return A named list of parameters.
#' @export
#' @examples
#' draw_parameters(model = make_model("X->Y"))
#'
draw_parameters <- function(model, using = NULL){
  
  if(is.null(using)) using <- "priors"
  
  if(!(using %in% c("priors", "posteriors", "parameters"))) stop(
    "`using` should be one of `priors`, `posteriors`, or `parameters`")
  
  if(using == "parameters") {if(is.null(model$parameters)) stop("No parameters provided")
    return(model$parameters)}
  
  if(using == "posteriors") {if(is.null(model$posterior)) stop("No posterior provided")
    param_dist <- extract(model$posterior, pars= "lambdas")$lambdas
    return(param_dist[sample(nrow(param_dist),1),])
  }
  
  if(is.null(model$priors)) {model <- set_priors(model)
  message(paste("Priors missing from model. Generated on the fly."))
  }
  
  if(is.null(model$P)) {model <- set_parameter_matrix(model)
  message(paste("Parameter matrix missing from model. Generated on the fly."))
  }
  
  lambdas_prior <- model$priors
  param_set     <- attr(model$P, "param_set")
  
  if(length(lambdas_prior) != length(param_set)) stop("parameters priors should have same length as parameter set")
  
  param_sets         <- unique(param_set)
  
  # Draw parameters, given priors
  parameters <- unlist(sapply(param_sets, function(v){
    i <- which(startsWith(names(lambdas_prior), paste0(v,".")))
    rdirichlet(1, lambdas_prior[i])}))
  names(parameters) <- names(lambdas_prior)
  parameters
}
