#' Get causal types
#'
#' Create a data frame with types produced from all combinations of possible data produced by a DAG.
#'
#' @param model A model object generated by \code{make_model()}.
#' @return A data frame.
#' @export
#'
get_causal_types <- function(model){
  if(!is.null(model$causal_types)){
    return_df <- model$causal_types
  } else {
    return_df <- update_causal_types(model)
  }
  return(return_df)
}

