

#' Get list of parents in a dag
#'
#' @param model A probabilistic causal model object generated by \code{make_model()}.
#' @export
#' @return A list of parents in a DAG
#' @examples
#' model <- make_model('X -> K -> Y')
#' get_parents(model)

get_parents <- function(model) {
	dag <- model$dag
	sapply(model$nodes, function(j)
		paste(dag$parent)[paste(dag$children) == j])
}
