
#' Produces the possible permutations of a set of variables
#'
#' @param max A vector of integers indicating the maximum value of an integer value starting at 0. Defaults to 1. The number of permutation is defined by \code{max}'s length
#' @export
#' @return A matrix of permutations
#' @importFrom rlang exprs
#' @examples
#'
#' \dontrun{
#' perm(3)
#' }
# perm <- function(v) {
# 	sapply(1:length(v), function(x) {
# 		rep(rep(1:v[x], each = prod(v[x:length(v)])/v[x]), length.out = prod(v))
# 	}) - 1
# }
perm <- function(max = rep(1, 2)){
	grid <- sapply(max, function(m) exprs(0:!!m))
	perm <- do.call(expand.grid, grid)
	colnames(perm) <- NULL
	perm
}

#' Get string between two regular expression patterns
#'
#' Returns a substring enclosed by two regular expression patterns. By default returns the name of the arguments being indexed by squared brackets (\code{[]}) in a string containing an expression.
#'
#' @param x A character vector of length 1L.
#' @param left A regular expression to serve as look ahead.
#' @param right A regular expression to serve as a look behind.
#' @return A character vector.
#' @export
#' @examples
#' a <- "(XX[Y=0] == 1) > (XX[Y=1] == 0)"
#' st_within(a)
#' b <- "(XXX[[Y=0]] == 1 + XXX[[Y=1]] == 0)"
#' st_within(b)

st_within <- function(x, left = "[[:punct:]]|\\b", right = "\\[", rm_left = 0, rm_right=-1){
	if(!is.character(x)) stop("`x` must be a string.")
	puncts <- gregexpr(left, x, perl = TRUE)[[1]]
	stops <- gregexpr(right, x, perl = TRUE)[[1]]

	# only index the first of the same boundary
	# when there are consecutive ones (eg. "[[")
	consec_brackets <- diff(stops)
	if(any(consec_brackets == 1)){
		remov <- which(consec_brackets == 1) + 1
		stops <- stops[-remov]
	}

	# find the closest punctuation or space
	starts <- sapply(stops, function(s){
		dif <- s - puncts
		dif <- dif[dif>0]
		ifelse(length(dif) == 0, ret <- NA, ret <- puncts[which(dif==min(dif))])
		return(ret)
	})
	drop <- is.na(starts) | is.na(stops)
	sapply(1:length(starts), function(i) if(!drop[i]) substr(x, starts[i]+rm_left, stops[i]+rm_right))
}

#' Recursive substitution
#'
#' Applies \code{gsub()} from multiple patterns to multiple replacements with 1:1 mapping.
#'
#' @param x A character vector.
#' @param pattern_vector A character vector.
#' @param replacement_vector A character vector.
#'
gsub_many <- function(x, pattern_vector, replacement_vector, ...){
	if(!identical(length(pattern_vector), length(replacement_vector))) stop("pattern and replacement vectors must be the same length")
	for(i in seq_along(pattern_vector)){
		x <- gsub(pattern_vector[i], replacement_vector[i], x, ...)
	}
	x
}

#' Generate type matrix
#' @param parent_n An integer. Number of parents of a given child.
#'
type_matrix <- function(parent_n){
	type_mat <- perm(rep(1, 2^parent_n))
	if(parent_n == 0){
		labels <- NULL
	} else {
		input_mat <- perm(rep(1, parent_n))
		labels <- apply(input_mat,1,paste,collapse = "")
	}
	colnames(type_mat) <- labels
	return(type_mat)
}

#' Clean condition
#'
#' Takes string specifying condition and returns properly spaced string.
#' @param condition A character string. Condition that refers to a unique position (posible outcome) in a nodal type.
clean_condition <- function(condition){
	spliced <- strsplit(condition, split = "")[[1]]
	spaces <- grepl("[[:space:]]", spliced, perl = TRUE)
	paste(spliced[!spaces], collapse = " ")
}

#' Interpret or find position
#'
#' Interprets the causal type of a given position in node, or returns positions that correspond to given condition.
#' @param model A model object generated by \code{make_model()}.
#' @param condition
#' @param position
#' @export
lookup_type <- function(model, condition = NULL, position = NULL){
	if(sum(!is.null(condition) & !is.null(position))>1)
		stop("Must specify either `query` or `nodal_position`, but not both.")
	parents <- get_parents(model)
	types <- lapply(lapply(parents, length), function(l) perm(rep(1, l)))

	if(is.null(position)){
		position <- lapply(types, function(i) ifelse(length(i)==0, return(NA), return(1:nrow(i))))
	}else{
		if(!all(names(position) %in% names(types))) stop("One or more names in `position` not found in model.")
	}

	interpret <- lapply(1:length(position), function(i){
		positions <- position[[i]]
		type <- types[[names(position)[i]]]
		pos_elements <- type[positions,]

		if(!all(is.na(positions))){
			interpret <- sapply(1:nrow(pos_elements), function(row)
				paste0(parents[[names(position)[i]]], " = ", pos_elements[row,], collapse = " & "))
			interpret <- paste0(paste0(c(names(position)[i], " | "), collapse = ""), interpret)
			# Create "Y*[*]**"-type representations
			asterisks <- rep("*", nrow(type))
			asterisks_ <- sapply(positions, function(s){
				if(s < length(asterisks)){
					if(s == 1) paste0(c("[*]", asterisks[(s+1):length(asterisks)]), collapse = "")
					else paste0(c(asterisks[1:(s-1)], "[*]", asterisks[(s+1):length(asterisks)]), collapse = "")
				} else {
					paste0(c(asterisks[1:(s-1)], "[*]"), collapse = "")
				}
			})
			display <- paste0(names(position)[i], asterisks_)
		} else {
			interpret <- paste0(
				paste0(c(names(position)[i], " = "), collapse = ""),
				c(0,1))
			display <- paste0(names(position)[i], c(0,1))
		}
		data.frame(variable = names(position)[i],
							 position = position[[i]],
							 display = display,
							 interpretation = interpret, stringsAsFactors = FALSE)
	})

	names(interpret) <- names(position)

	if(!is.null(condition)){
		conditions <- sapply(condition, clean_condition)
		interpret_ <- lapply(interpret, function(i){
			slct <- sapply(conditions, function(cond){
				a <- trimws(strsplit(cond, "&|\\|")[[1]])
				sapply(i$interpretation, function(bi){
					b <- trimws(strsplit(bi, "&|\\|")[[1]])
					all(a %in% b)
				})
			})
			i <- i[rowSums(slct) > 0,]
			if(nrow(i)==0) i <- NULL
			i
		})
		interpret <- interpret_[!sapply(interpret_, is.null)]
	}

	return(interpret)
}

#' Expand wildcard
#'
#' Expand statement containing wildcard
#'
#' @param to_expand A character vector of length 1L.
#' @param join_by A character vector of length 1L.
#' @export
#'
expand_wildcard <- function(to_expand, join_by = "|"){
	orig <- st_within(to_expand, left= "\\(", right="\\)", rm_left = 1)
	skeleton <- gsub_many(to_expand, orig, paste0("%expand%", 1:length(orig)),
												fixed = TRUE)
	expand_it <- grepl("\\.", orig)

	expanded_types <- lapply(1:length(orig), function(i){
		if(!expand_it[i])
			return(orig[i])
		else {
			exp_types <- strsplit(orig[i], ".", fixed = TRUE)[[1]]
			a <- gregexpr("\\w{1}\\s*(?=(=\\s*\\.){1})", orig[i], perl = TRUE)
			matcha <- trimws(unlist(regmatches(orig[i], a)))
			rep_n <- sapply(unique(matcha), function(e) sum(matcha == e))
			n_types <- length(unique(matcha))
			grid <- replicate(n_types, expr(c(0,1)))
			type_values <- do.call(expand.grid, grid)
			colnames(type_values) <- unique(matcha)

			apply(type_values, 1, function(s){
				to_sub <- paste0(colnames(type_values), "(\\s)*=(\\s)*$")
				subbed <- gbiqq:::gsub_many(exp_types, to_sub, paste0(colnames(type_values), "=", s), perl = TRUE)
				paste0(subbed, collapse = "")
			})
		}
	})

	if(!is.null(join_by)){
		oper <- sapply(expanded_types, function(l){
			paste0(l, collapse = paste0(" ", join_by, " "))
		})
		if(length(orig)==1 && length(orig)!=length(oper)){
			oper <- sapply(expanded_types, function(a) gsub("%expand%1", a, skeleton))
			oper_return <- paste0(oper, collapse = paste0(" ", join_by, " "))
		}else{
			oper_return <- gsub_many(skeleton,paste0("%expand%", 1:length(orig)), oper)
		}

	} else {
		oper <- do.call(cbind, expanded_types)
		oper_return <- apply(oper, 1, function(i) gsub_many(skeleton,
																												paste0("%expand%", 1:length(orig)),i))
	}
	cat("Generated expanded expression:\n")
	cat(unlist(oper_return), sep = "\n")
	oper_return
}


