#' Helpers for inspecting causal models
#'
#' Various helpers to inspect or access internal objects generated or used by Causal Models
#'
#' @name inspection
NULL
#> NULL

#' inspect a causal model
#'
#' Returns specified elements from a \code{causal_model} and prints summary.
#' Users can use \code{inspect} to extract model's components or objects implied by
#' the model structure including nodal types, causal types, parameter priors,
#' parameter posteriors, type priors, type posteriors, and other relevant elements.
#' See argument \code{what} for other options.
#' @rdname inspection
#' @inheritParams CausalQueries_internal_inherit_params
#' @param what A character string or vector specifying the component(s) to
#'   retrieve. If \code{NULL} (the default), returns a model summary. If a
#'   vector, returns a named list of components (length-1 still unwraps to
#'   the component itself). Available options are:
#'   \itemize{
#'   \item "\code{statement}" a character string describing causal relations using arrow syntax (e.g. \code{"X -> Y"}),
#'   \item "\code{nodes}" A list containing the nodes in the model,
#'   \item "\code{parents_df}" A table listing nodes, whether they are root nodes or not, and the number and names of parents they have,
#'   \item "\code{parameters}" A vector of 'true' parameters,
#'   \item "\code{parameter_names}" A vector of names of parameters,
#'   \item "\code{parameter_mapping}" A matrix mapping from parameters into data types,
#'   \item "\code{parameter_matrix}" A matrix mapping from parameters into causal types,
#'   \item "\code{parameters_df}" A data frame containing parameter information,
#'   \item "\code{causal_types}" A data frame listing causal types and the nodal types that produce them,
#'   \item "\code{nodal_types}" A list with the nodal types of the model,
#'   \item "\code{data_types}" A list with all data types consistent with the model; for options see \code{?get_all_data_types},
#'   \item "\code{ambiguities_matrix}" A matrix mapping from causal types into data types,
#'   \item "\code{prior_hyperparameters}" A vector of alpha values used to parameterize Dirichlet prior distributions; optionally provide node names to reduce output, e.g., \code{inspect(prior_hyperparameters, nodes = c('M', 'Y'))},
#'   \item "\code{prior_distribution}" A data frame of draws from the parameter prior,
#'   \item "\code{posterior_distribution}" A data frame of draws from the parameter posterior,
#'   \item "\code{type_prior}" A matrix of causal-type probabilities under the parameter prior,
#'   \item "\code{type_posterior}" Posterior draws over causal types (draws \eqn{\times} types).
#'     Retained only after legacy updates with \code{keep_type_distribution = TRUE}
#'     (\code{keep_type_distribution} is the \code{update_model} flag; the stored
#'     object is always named \code{type_posterior}). Factorized updates never
#'     store it; use \code{posterior_distribution} and
#'     \code{query_model(..., using = "posteriors")}, or re-update with
#'     \code{legacy = TRUE},
#'   \item "\code{prior_event_probabilities}" Complete-data event probabilities \code{w} given a single parameter realization (not coarsened \code{w_full}); see \code{?get_event_probabilities},
#'   \item "\code{posterior_event_probabilities}" Posterior draws of complete-data event probabilities \code{w} (retained when \code{keep_event_probabilities = TRUE}),
#'   \item "\code{data}" A data frame with data that was provided to update the model,
#'   \item "\code{stan_summary}" A `stanfit` summary with processed parameter names,
#'   \item "\code{stanfit}" An (unprocessed) \code{stanfit} object as generated by Stan, with raw parameter names,
#'   \item "\code{stan_warnings}" Messages generated during the generation of a \code{stanfit} object.
#'   }
#' @param ... Other arguments passed to helper \code{"get_*"} functions: get_all_data_types, get_event_probabilities,  get_priors, Any such additional arguments must be named.
#' @return Objects  that can be derived from a \code{causal_model}, with summary.
#'   The type of the return value depends on \code{what}.
#'
#' @export
#'
#' @examples
#' \donttest{
#'
#' model <- make_model("X -> Y")
#' data <- make_data(model, n = 4)
#'
#' inspect(model, what = "statement")
#' inspect(model, what = "parameters")
#' inspect(model, what = "nodes")
#' inspect(model, what = "parents_df")
#' inspect(model, what = "parameters_df")
#' inspect(model, what = "causal_types")
#' inspect(model, what = "prior_distribution")
#' inspect(model, what = "prior_hyperparameters", nodes = "Y")
#' inspect(model, what = "prior_event_probabilities", parameters = c(.1, .9, .25, .25, 0, .5))
#' inspect(model, what = "prior_event_probabilities", given = "Y==1")
#' inspect(model, what = "data_types", complete_data = TRUE)
#' inspect(model, what = "data_types", complete_data = FALSE)
#'
#'
#' model <- update_model(model,
#'   data = data,
#'   keep_fit = TRUE,
#'   keep_event_probabilities = TRUE)
#'
#' inspect(model, what = "posterior_distribution")
#' inspect(model, what = "posterior_event_probabilities")
#' inspect(model, what = "type_posterior")
#' inspect(model, what = "data")
#' inspect(model, what = "stan_warnings")
#' inspect(model, what = "stanfit")
#' }
#'
inspect <- function(model, what = NULL, ...)
  .inspect.grab(model, what = what, print = TRUE, ...)


#' access objects from a causal model
#'
#' Returns specified elements from a \code{causal_model}.
#' Users can use \code{inspect} to extract model's components or objects implied by
#' the model structure including nodal types, causal types, parameter priors,
#' parameter posteriors, type priors, type posteriors, and other relevant elements.
#' See argument \code{what} for other options.
#'
#' @rdname inspection
#' @inheritParams CausalQueries_internal_inherit_params
#' @param what A character string or vector specifying the component(s) to
#'   retrieve. If \code{NULL} (the default), returns a model summary. If a
#'   vector, returns a named list of components (length-1 still unwraps to
#'   the component itself). Available options are:
#'   \itemize{
#'   \item "\code{statement}" a character string describing causal relations using arrow syntax (e.g. \code{"X -> Y"}),
#'   \item "\code{nodes}" A list containing the nodes in the model,
#'   \item "\code{parents_df}" A table listing nodes, whether they are root nodes or not, and the number and names of parents they have,
#'   \item "\code{parameters}" A vector of 'true' parameters,
#'   \item "\code{parameter_names}" A vector of names of parameters,
#'   \item "\code{parameter_mapping}" A matrix mapping from parameters into data types,
#'   \item "\code{parameter_matrix}" A matrix mapping from parameters into causal types,
#'   \item "\code{parameters_df}" A data frame containing parameter information,
#'   \item "\code{causal_types}" A data frame listing causal types and the nodal types that produce them,
#'   \item "\code{nodal_types}" A list with the nodal types of the model,
#'   \item "\code{data_types}" A list with all data types consistent with the model; for options see \code{?get_all_data_types},
#'   \item "\code{ambiguities_matrix}" A matrix mapping from causal types into data types,
#'   \item "\code{prior_hyperparameters}" A vector of alpha values used to parameterize Dirichlet prior distributions; optionally provide node names to reduce output, e.g., \code{inspect(prior_hyperparameters, nodes = c('M', 'Y'))},
#'   \item "\code{prior_distribution}" A data frame of draws from the parameter prior,
#'   \item "\code{posterior_distribution}" A data frame of draws from the parameter posterior,
#'   \item "\code{type_prior}" A matrix of causal-type probabilities under the parameter prior,
#'   \item "\code{type_posterior}" Posterior draws over causal types (draws \eqn{\times} types).
#'     Retained only after legacy updates with \code{keep_type_distribution = TRUE}
#'     (\code{keep_type_distribution} is the \code{update_model} flag; the stored
#'     object is always named \code{type_posterior}). Factorized updates never
#'     store it; use \code{posterior_distribution} and
#'     \code{query_model(..., using = "posteriors")}, or re-update with
#'     \code{legacy = TRUE},
#'   \item "\code{prior_event_probabilities}" Complete-data event probabilities \code{w} given a single parameter realization (not coarsened \code{w_full}); see \code{?get_event_probabilities},
#'   \item "\code{posterior_event_probabilities}" Posterior draws of complete-data event probabilities \code{w} (retained when \code{keep_event_probabilities = TRUE}),
#'   \item "\code{data}" A data frame with data that was provided to update the model,
#'   \item "\code{stan_summary}" A `stanfit` summary with processed parameter names,
#'   \item "\code{stanfit}" An (unprocessed) \code{stanfit} object as generated by Stan, with raw parameter names,
#'   \item "\code{stan_warnings}" Messages generated during the generation of a \code{stanfit} object.
#'   }
#' @param ... Other arguments passed to helper \code{"get_*"} functions: get_all_data_types, get_event_probabilities,  get_priors, Any such additional arguments must be named.
#' @return Quiet return of objects that can be derived from a \code{causal_model}.
#'   The type of the return value depends on \code{what}.
#'
#' @export
#'
#' @examples
#' model <- make_model("X -> Y")
#'
#' x <- grab(model, what = "statement")
#' x

grab <- function(model, what = NULL, ...)
  .inspect.grab(model, what = what, print = FALSE, ...)

#' Helper for inspecting causal models
#' @keywords internal
#' @noRd

.inspect.grab <- function(model, what = NULL, print = TRUE, ...) {

  cat <- model_component_catalogue()
  .large <- cat$on_demand

  # No `what`: report (and return) the whole model summary
  if (is.null(what)) {
    model_sum <- summary(model, ...)

    if (print) print(model_sum)

    return(invisible(model_sum))
  }

  check_model_component_names(what, cat)

  include <- base::intersect(what, .large)

  if (length(include) > 0) {
    model_sum <- summary(model, include = include, ...)
  } else {
    model_sum <- summary(model, ...)
  }

  if (print) print(model_sum, what = what)

  extract_one <- function(w) {
    if (w == "type_posterior") {
      tp <- model_sum[["stan_objects"]][["type_posterior"]]
      if (is.null(tp)) {
        stop(type_posterior_unavailable_msg(model_sum), call. = FALSE)
      }
      return(tp)
    }
    if (w %in% c("stanfit", "data",
                 "stan_summary", "stan_warnings")) {
      model_sum[["stan_objects"]][[w]]
    } else if (w == "posterior_event_probabilities") {
      model_sum[["stan_objects"]][["event_probabilities"]]
    } else if (!is.null(model_sum[[w]])) {
      model_sum[[w]]
    } else {
      stop("The following requested object is not supported: ", w)
    }
  }

  if (length(what) == 1) {
    return(invisible(extract_one(what)))
  }

  out <- lapply(what, extract_one)
  names(out) <- what

  return(invisible(out))

}

