
#' Get list of parents in a dag
#'
#' @param model A probabilistic causal model object generated by \code{make_model()}.
#' @export
#' @return A list of parents in a DAG
#' @examples
#' model <- make_model("X -> K -> Y")
#' get_parents(model)

get_parents <- function(model) {
	dag <- model$dag
	sapply(paste(unique(unlist(dag))), function(j) paste(dag$parent)[paste(dag$children) == j])
}

#' Get causal types
#'
#' Create a data frame with types produced from all combinations of possible data produced by a DAG.
#'
#' @param model A model object generated by \code{make_model()}.
#' @return A data frame.
#' @export
#'
get_causal_types <- function(model){
	if(!is.null(model$causal_types)){
		return_df <- model$causal_types
	} else {
		return_df <- update_causal_types(model)
	}}
