
#' Lookup nodal types according to a query
#'
#' @param model A model object generated by \code{make_model()}.
#' @param query A character vector of length 1L. An expression in string format defining causal types to interrogate \code{reveal_outcomes()}
#' @param join_by A string. The logical expression connecting expanded types, _AND_ ("&") or _OR_ ("|"). Defaults to "|".
#' @export
#' @return A list containing the types and the evaluated expression. `manipulated_outcomes` are the variables on the left of a [] expression
#' @examples
#' model <- make_model("X -> M -> Y; X->Y")
#' query <- "(Y[X= 1] > Y[X=0])"
#' x <- get_types(model, query)
#' summary(x)
#'
#'
#'
lookup_type <- function(model, query, join_by = "|"){

	# Add
	w_query <- gsub("\\(|\\)", "", query)
	w_query <- str_split(	w_query, "\\==|>|<|>=|<=|\\&|\\|")
	w_query <- sapply(unlist(w_query), function(x) trimws(x))
  w_query <- sapply(w_query,function(q){

 	var <- st_within(q)
 	if(!var %in% model$variables)
 		stop(paste0("Variable "), var, " not in model")
 	v_parents <- get_parents(model)[[var]]
 	nnn <- !str_detect(q, v_parents)
 	not_in <- v_parents[nnn]
 	q <- gsub("\\]", paste0(",",  	not_in , " = .\\]"), q)
 	})
  qqq <- names(w_query) != w_query
  to_rep <- w_query[qqq]
  .query <-  query2 <- query
  for (i in 1:length(to_rep)) {

  	ytt <-trimws(gsub(paste0("\\[|\\]|",var), "", names(to_rep)[i]))
  	ytt <- paste0(var, "\\[", ytt, "\\]" )
  	.query <- gsub(	ytt,to_rep[i], .query)
  	query2 <- gsub(	ytt,paste0("`",to_rep[i],"`"), query2)
  }

 if(grepl(".", .query, fixed = TRUE)){
 	.query <- expand_wildcard(.query, join_by = join_by)
  query2 <- capture.output( expand_wildcard(query2, join_by = join_by))[2]
  }
  .w_query <- gsub("\\(|\\)", "",   .query )
  .w_query <- str_split(	.w_query, "\\==|>|<|>=|<=|\\&|\\|")
  .w_query <- sapply(unlist(.w_query), function(x) trimws(x))



  revealed_outcomes <- lapply(.w_query, function(wq)  lookup_type_single(model, query = wq))
  df <- do.call(cbind, revealed_outcomes)
  colnames(df) <- sapply(names(revealed_outcomes), trimws)
  value <- c(eval(parse(text = query2), envir =  df))
}




lookup_type_single <- function(model, query){

	w_query         <- gsub(" ", "", query)
	w_query         <- unlist(strsplit(query, ""))
	bracket_starts  <- grep( "\\[", w_query)
	bracket_ends    <- grep( "\\]", w_query)
	.query        	<- w_query[(bracket_starts):bracket_ends]
	brackets <- grepl("\\[|\\]",  .query)
	.query   <- .query[!brackets]
	.query   <-  paste0(.query, collapse = "")
	.query   <- unlist(strsplit(.query, ","))

	dos <- sapply(.query, function(q) {
		do <- unlist(strsplit( q, ""))
		stop <- gregexpr("=", q, perl = TRUE)[[1]][1]  - 1
		var_name <-  paste0(do[1:stop], collapse = "")
		var_name <- gsub(" ", "", var_name)
		value <- paste0(do[(stop +2):nchar(q)], collapse = "")
		vars  <-  model$variables
		if(!var_name %in% vars) 	stop(paste("Variable", var_name ,"is not part of the model."))
	  out <- value
	  names(out) <- var_name
	  out
	}, USE.NAMES = FALSE)

	b <- 1:bracket_starts
	var <- paste0(w_query[b], collapse = "")
	var <- st_within(var)


	revaled_variables <- reveal_outcomes(model, dos, node = var)[var]


  return(revaled_variables)


}



#' @export
print.nodal_types <- function(x, ...) {
	print(summary(x))
	invisible(x)
}


#' @export
summary.nodal_types <- function(object, ...) {
	structure(object, class = c("summary.causal_types", "data.frame"))

}

#' @export
print.summary.nodal_types <- function(x, ...){
	output_type <- class(x$types)
  types_labels <- names(x$types)[x$types]
		cat(paste("\nNodal types satisfying query's condition(s)  \n\n query = ", x$query,  "\n\n"))

		if(length(types1) %% 2 != 0){
			types_labels[length(types_labels ) + 1] <- ""
		}
		counter <- 2
		while (counter <= length(types_labels ) ) {
			cat(paste0(names(types_labels [(counter -1):counter]), collapse = "  "))
			cat("\n")
			counter <- counter + 2
		}

		cat(paste("\n\n Number of nodal types that meet condition(s) = ", length(types_labels)))
		cat(paste("\n Total number of nodal types related to", node,"= ", length(x$types)))

}



