#' Print a tightened summary of model queries
#'
#' print method for class \code{model_query}.
#'
#' @param x An object of \code{model_query} class.
#' @param ... Further arguments passed to or from other methods.
#'
#' @seealso \code{\link{plot.model_query}} for a graphical display of the same object.
#'
#' @rdname print.model_query
#' @keywords internal
#' @export
#'
print.model_query <- function(x, ...) {
  cred.low <- NULL
  cred.high <- NULL
  case_level <- NULL
  given <- NULL

  if(any("posteriors" %in% x$using)){
    if(any(attr(x, "stan_warnings") != "")) {
      cat("Note: warnings passed from rstan during updating:\n")
      cat(attr(x, "stan_warnings"))
      cat("\n")
    }}

  text1 <- "Causal queries generated by query_model"

  # Output simplification
  if (all(c("using", "case_level", "sd", "given") %in% names(x))) {
    if (all(x$using == "parameters" | x$case_level)) {
      x <- x |>
        dplyr::select(-sd, -cred.low, -cred.high)
    }
    if (all(x$given == "-")) {
      x <- x |>
        dplyr::select(-given)
    }
    if (all(!x$case_level)) {
      x <- x |>
        dplyr::select(-case_level)
      text1 <- paste(text1, "(all at population level)")
    }
  }
  if (all(c("query", "label", "given") %in% names(x))) {
    if(all(x$query == x$label)) x <- select(x, -label)
    if(all(x$label == paste(x$query, ":|:", x$given))) x <- dplyr::select(x, -all_of(c("query", "given")))
  }

  if (all(c("query", "label") %in% names(x))  &  !("given" %in% names(x))) {
    if(all(x$label == x$query)) x <- dplyr::select(x, -all_of("query"))
  }

  # Printout requires modification for markdown disambiguation
  r <- x
  cat("\n")
  cat(text1)
  r$label <- clean_text(r$label)
  r$query <- clean_text(r$query)
  r$given <- clean_text(r$given)
  print(knitr::kable(r, digits = 3))
  cat("\n")

  return(invisible(x))
}


# Helper function to clean up the text
clean_text <- function(column) {
  if (!is.null(column)) {
    column <- gsub("\\|", "OR", column)
    column <- gsub(":OR:", " given ", column)
    gsub("\\s+", " ", column)  # Return the cleaned column
  } else {
    NULL
  }
}




#' Summarizing model queries
#'
#' summary method for class "\code{model_query}".
#'
#' @param object An object of \code{model_query} class produced using
#'   \code{query_model}
#' @param ... Further arguments passed to or from other methods.
#'
#' @return Returns the object of class \code{summary.model_query}
#'
#' @examples
#' \donttest{
#' model <-
#'   make_model("X -> Y") |>
#'   query_model("Y[X=1] > Y[X=1]")  |>
#'   summary()
#'}
#'
#' @export
summary.model_query <- function(object, ...) {
  class(object) <- c("summary.model_query", class(object))
  object
}


#' @rdname summary.model_query
#'
#' @param x an object of \code{model_query} class produced using
#'  \code{query_model}
#' @param ... Further arguments passed to or from other methods.
#'
#' @export

print.summary.model_query <- function(x, ...) {
  print_call_and_date(x)
  print.model_query(x)
}

# Helper function to print the call and date attributes
#'
#' @noRd
#' @keywords internal
print_call_and_date <- function(object) {
  cat("Call: \n")
  cat(paste(deparse(attr(object, "call")), collapse = " "), "\n")

  cat("\nQueries evaluated on: \n")
  cat(attr(object, "date"))
  cat("\n")
}


