#' Add a true parameter vector
#'
#' Add a vector of "true" parameters to a model.
#'
#' @param model A model generated by \code{make_model}.
#' @param parameters A numeric vector. Parameters to add to model.
#' @param type A character string specifying type of parameters to set ("flat", "prior_mean", "posterior_mean", "prior_draw", "posterior_draw", "define). With type set to \code{define} use arguments to be passed to \code{make_priors}; otherwise \code{flat} sets equal probabilities on each nodal type in each parameter set; \code{prior_mean}, \code{prior_draw}, \code{posterior_mean}, \code{posterior_draw} take parameters as the means or as draws from the prior or posterior.
#' @param warning Logicial indicates whether to warn about parameter renormalization
#' @param ... Options passed onto \code{make_priors()}.
#' @importFrom rstan extract
#' @export
#' @examples
#' model <- make_model("X -> Y")
#' get_parameters(model)
#' set_parameters(model, parameters = c(.25, .75, 1.25,.25, .25, .25)) %>% get_parameters
#' set_parameters(make_model("X -> Y"), type = "flat") %>% get_parameters
#'
#' # Use priors arguments to define specific parameters using causal syntax
#' set_parameters(make_model("X -> Y"),
#'                statement = "Y[X=1]>Y[X=0]", alphas = 2) %>%
#'                get_parameters
#' make_model("X -> Y") %>%
#'    set_parameters(statement = c("Y[X=1]>Y[X=0]", "Y[X=1]<Y[X=0]"), alphas = c(2,0)) %>%
#'    get_parameters
#' make_model("X -> Y") %>%
#'   set_confound(list(X = "Y[X=1]>Y[X=0]"))  %>%
#'   set_parameters(confound = list(X="Y[X=1]>Y[X=0]", X="Y[X=1]<=Y[X=0]"),
#'                  alphas = list(c(.2, .8), c(.8, .2))) %>%
#'   set_parameters(statement = "Y[X=1]>Y[X=0]", alphas = .5) %>%
#'   get_parameters


set_parameters <- function(model,
													 parameters = NULL,
													 type = NULL,
													 warning = TRUE,
													 ...) {
	# Figure out if we need to use make_priors
  prior_args = list(...)

  prior_args_provided <- sum(names(prior_args) %in% c("distribution", "alphas", "node", "label", "statement", "confound"))
  if(prior_args_provided >0 & is.null(type)) type <- "define"

  if(is.null(type)) type  <- 	"prior_mean"


  # If parameters provided, clean and use these and then exit
	if(!is.null(parameters)){
		model$parameters_df$parameters <- parameters
		model$parameters_df <- check_params(model$parameters_df, warning = warning)
		return(model)
	}

	# Flat lambda
	if (type == "flat")  {
		parameters <- make_priors(model, distribution = "uniform")
	}

	# New (from alpha)
	if (type == "define") {
		# This is needed so that use of make_priors adjust parameters, not priors
		model_temp <- model
		model_temp$parameters_df$priors <- model_temp$parameters_df$parameters
		parameters <- make_priors(model_temp, ...)
	}

	# Prior mean
	if (type == "prior_mean") {
		parameters <- get_priors(model)
	}

	# Prior draw
	if (type == "prior_draw") {
		parameters <- draw_parameters(model)
	}

	if (type == "posterior_mean") {
		if (is.null(model$posterior)) stop("Posterior distribution required")
		parameters <- apply(extract(model$posterior, pars = "lambdas")$lambdas, 2, mean)
	}

	if (type == "posterior_draw") {
		if (is.null(model$posterior)) stop("Posterior distribution required")
		df <- extract(model$posterior, pars = "lambdas")$lambdas
		parameters <- df[sample(nrow(df), 2),]
	}

	model$parameters_df$parameters <- parameters
	model$parameters_df <- check_params(model$parameters_df, warning = FALSE)
	model

}


#' Get parameters
#'
#' Extracts parameters as a namesd vector
#'
#' @param model A model object generated by make_model().
#'
#' @export
#' @examples
#' get_parameters(make_model("X -> Y"))

get_parameters  <- function(model) {

	x <- model$parameters_df$parameters
	names(x) <- model$parameters_df$param_names
	x

}

