#' Make alphas
#'
#' Stipulated alpha values override prior_distribution
#' @param model A model object generated by \code{make_model()}.
#' @param alphas A numeric vector. Hyperparameters of the Dirichlet distribution to be passed to \code{make_priors()}.
#' @export

make_alphas <- function(model, alphas = NULL ){

#	if(is.null(model$P)) 	{model  <- set_parameter_matrix(model)}
#	P                  <- model$P
	return_alphas      <- alphas
	par_names          <- get_parameter_names(model, include_paramset = FALSE)
#	alpha_names        <- names(unlist(alphas))
	alpha_names        <- 	unlist(lapply(alphas, names))
	pars_in_alpha      <- alpha_names %in% par_names

  # if alpha is defined as vector of queries alphas <- c(`(Y[X=1] == Y[X=0])`  = 3,  `X == 1` = 3  )
  if(is.numeric(alphas) & !is.null(alpha_names)){
  	return_alphas  <-   query_to_parameters(model,	 alphas)
  }


	# if alpha contain other than parameter names e.g alphas = list(X = c(X0 = 2, `X == 1` = 3))
  if(is.list(alphas)  & any(! pars_in_alpha)){
  # Prep and translate alpha
 	i_queries <- which(!pars_in_alpha)
 	alpha_query <- unlist(alphas)[i_queries]
 	queries <- names(alpha_query)
  names(alpha_query) <- 	sapply(queries, function(q){
  	stop <- gregexpr("\\.", q, perl = TRUE)[[1]][1]
  	substr(q, stop + 1, nchar(q))
  })

 	translated_alphas  <-  gbiqq:::query_to_parameters(model, alpha_query)

 	# Lines below check for discrepancies
 	# ok alphas(Y = c(Y00 = 1, `(Y[X=1] == Y[X=0])` = 1)
 	# error  alphas(Y = c(Y00 = 2, `(Y[X=1] == Y[X=0])` = 1) --two arguments pointing at the same parameter
 	error_message <- gbiqq:::any_discrepancies(alphas, translated_alphas)
  if(!is.null(error_message))	{
  	stop("\n Please solve the following discrepancies \n", paste(error_message))
  }
 	# Get alphas that were specificied as par_names as opposed to queries
 	alpha_param <- sapply(alphas, function(a){
 	#	a[names(a) %in% rownames(P)]

 		a[names(a) %in% par_names]

 	}, simplify = FALSE)

 	# combine translated alphas and alpha_parameters by parameter set
 	return_alphas <- gbiqq:::combine_lists(list1 = alpha_param, list2 =translated_alphas)
 }
  return_alphas
}


#' Make priors
#'
#' @param model A model created by \code{make_model()}
#' @param prior_distribution A character indicating the prior distribuiton
#' @param alphas the hyperparameters of the dirichlet distribution.
#' Stipulated alpha values override prior_distribution
#' @export
#' @examples
#' model <- make_model("X -> Y")
#' # Default sets all priors to 1
#' make_priors(model = model)
#' # Set all priors to 0.5
#' make_priors(model = model, prior_distribution = "jeffreys")
#' # Set all priors to infinity
#' make_priors(model = model, prior_distribution = "certainty")
#' # Set all priors to 1 except for prior of nodal_type X0
#' make_priors(model = model, alphas = list(X = c(X0 = 2)))
#' # Specify priors by query
#'  make_priors(model = model,
#'              alphas = c(`(Y[X=1] == Y[X=0])`  = 3,  `X == 1` = 3))
#' # Specify priors for each of the nodal_types in model
#' make_priors(model = model,
#'  alphas = list(X = c(X0 = 2, `X == 1` = 3),
#'  Y = c(`(Y[X=1] > Y[X=0])` = 3,
#'  Y10 = 2, `(Y[X=1] == Y[X=0])` = 3)))
#' # set all priors to 10
#' make_priors(model = model, alphas =  10)
#' # If the prior for a given parameter is duplicated,
#' # make_prior() throws an informative error.
#' \dontrun{
#' make_priors(model = model,
#'  alphas = list(X = c(X0 = 2, `X == 1` = 3),
#'  Y = c(Y00 = 1, `(Y[X=1] > Y[X=0])` = 3,
#'  Y01 = 2, `(Y[X=1] == Y[X=0])`  = 3)))
#'  }
#'
#' # Priors of confounded models
#' model <- make_model("X -> Y") %>%
#' set_confound(list(X = "(Y[X=1]>Y[X=0])"))
#'
#' # Simultaneously set priors for confound and nonconfound parameters.
#' make_priors(model = model,  alphas =  c(`(X == 0)`  = 2))
#' # To target variable modeling confound, specify the condition
#' # that determines the confounded relationship between variables
#' make_priors(model = model,  alphas =  c(`(X == 0) & (Y[X=1]>Y[X=0])` = 2))
make_priors  <- function(model,  prior_distribution = "uniform", alphas = NULL){

	if(!is.null(prior_distribution)){
		if(!(prior_distribution %in% c("uniform", "jeffreys", "certainty")))
				stop("prior_distribution should be either 'uniform', 'jeffreys', or 'certainty'.")
	}

	#if(is.null(model$P)) {model  <- set_parameter_matrix(model)}
	# P          <- get_parameter_matrix(model)
	par_names  <- get_parameter_names(model = model)
	n_params   <- length(par_names)
  alphas     <- make_alphas(model, alphas)


	# alpha housekeeping
	alphas_vector <- unlist(alphas)
	n_alphas      <- length(alphas_vector)
	alpha_names   <- names(alphas_vector)

	if(is.null(prior_distribution) & ((n_alphas!=1 & n_alphas!=n_params)))	stop(
		"if prior_distribution is not specified, alphas must contain either a value
		for each parameter or a single value to be assigned to all parameters.")


	if(n_alphas == 1 & is.null(alpha_names)){
		alphas_vector <- rep(alphas, n_params)
		names(alphas_vector) <- alpha_names   <- par_names
	}


	# Check that alpha names match par names
	not_in_dag <- !alpha_names %in% par_names
	if(any(not_in_dag )){
		index <- which(not_in_dag)
		error_text	<- sapply(index, function(i){

			reversed_name <- sapply(lapply(strsplit(alpha_names[i], NULL), rev), paste, collapse = "")
			splitted_name <- unlist( strsplit(sub("[.]", ";", reversed_name), ";"))

			paste0("\n variable ", splitted_name[2], " and corresponding nodal_type ",
						 splitted_name[1], " must match variables in dag and nodal_types syntax")

		})
		stop(	error_text )}

	# Check alpha strictly positive
	if(any(	alphas_vector  <= 0)) stop("alphas must be strictly positive real numbers")

	# Calculate priors
	if(!is.null(prior_distribution)){
		if(prior_distribution == "uniform")   priors <- rep(1, n_params )
		if(prior_distribution == "jeffreys")  priors <- rep(0.5, n_params )
		if(prior_distribution == "certainty") priors <- rep(10000, n_params )

	} else{
		if(n_alphas == 1)                     priors <- rep(alphas, n_params)
		if(n_alphas == n_params)              priors <- alphas}

	# Substitute alpha vector when provided
	names(priors)       <- par_names
	priors[alpha_names] <- alphas_vector

	# result
	names(priors)       <- par_names
	priors

}



#' Set prior distribution
#'
#' Set prior distribution. Use \code{make_alphas} to use causal types to indicate priors.
#' @param model A model object generated by \code{make_model()}.
#' @param priors A numeric vector. Dirichlet hyperparameters.
#' @param prior_distribution A character string. Indicates the prior distribution to be used. Can be 'uniform', 'jeffreys', or 'certainty'.
#' @param alphas A numeric vector. Hyperparameters of the Dirichlet distribution to be passed to \code{make_priors()}.
#' @export
#' @examples
#'
#' library(dplyr)
#' model <- make_model("X -> Y") %>%
#'   set_priors(
#'            alphas = list(
#'              X = c(`X == 1` = 3),
#'              Y = c(`(Y[X=1] != Y[X=0])` = 3)))
#'model$priors
#'
#'model <- make_model("X -> Y") %>%
#' set_priors(prior_distribution = "jeffreys")
#' model$priors
#'
#'model <- make_model("X -> Y") %>%
#' set_priors(1:6)
#' model$priors


set_priors  <- function(model,
												priors = NULL,
												prior_distribution = "uniform",
												alphas = NULL) {

	if(is.null(priors)) priors <- make_priors(model,
			                            					prior_distribution = prior_distribution,
																						alphas = alphas)

   model$parameters_df$priors  <- priors

   model

}



#' Get prior distribution
#'
#' @param model A model object generated by make_model().
#'
#' @export

get_priors  <- function(model) model$parameters_df$priors


#' Add prior distribution draws
#'
#' Add n_param x n_draws database of possible lambda draws to the model.
#'
#' @param model A model object generated by make_model().
#' @param n_draws A scalar. Number of draws.
#' @export
#' @examples
#' model <- make_model("X -> Y") %>% set_prior_distribution(5)
#' model$prior_distribution
#'
set_prior_distribution <- function(model, n_draws = 4000) {

  if(is.null(model$P)) model <- set_parameter_matrix(model)

  model$prior_distribution <- t(replicate(n_draws, draw_parameters(model)))

  model
}


#' Add a true parameter vector
#'
#' Add a vector of "true" parameters to a model.
#'
#' @param model A model generated by \code{make_model}.
#' @param parameters A numeric vector. Parameters to add to model.
#' @param type A character string specifying type of parameters to set ("flat", "prior_mean", "posterior_mean", "prior_draw", "posterior_draw", "define). With type set to \code{define} use arguments to be passed to \code{make_priors}; otherwise \code{flat} sets equal probabilities on each nodal type in each parameter set; \code{prior_mean}, \code{prior_draw}, \code{posterior_mean}, \code{posterior_draw} take parameters as the means or as draws from the prior or posterior.
#' @param ... Options passed onto \code{make_priors()}.
#' @importFrom rstan extract
#' @export
#' @examples
#' model <- make_model("X -> Y")
#' get_parameters(model)
#' set_parameters(model, parameters = c(.25, .75, 1.25,.25, .25, .25))$parameters_df
#' set_parameters(make_model("X -> Y"), type = "flat")$parameters
#'
#' # Use make_alpha to define specific parameters using causal syntax
#' model <- set_parameters(make_model("X -> Y"), type = 'define',
#'                         alphas = list(Y = c(`(Y[X=1] > Y[X=0])` = 3)))
#' model$parameters_df
set_parameters <- function(model,
													 parameters = NULL,
													 type = "prior_mean",
													 ...) {

  # If parameters provided, clean and use these and then exit
	if(!is.null(parameters)){
		model$parameters_df$parameters <- parameters
		model$parameters_df <- check_params(model$parameters_df, warning = TRUE)
    return(model)
    }

	# Flat lambda
	if (type == "flat")  {
		parameters <- make_priors(model, prior_distribution = "uniform")
		 }

	# New (from alpha)
	if (type == "define") {
		parameters <- make_priors(model, ...)
   }

	# Prior mean
	if (type == "prior_mean") {
		parameters <- model$parameters_df$priors
		}

	# Prior draw
	if (type == "prior_draw") {
			parameters <- draw_parameters(model)
			}

	if (type == "posterior_mean") {
			if (is.null(model$posterior)) stop("Posterior distribution required")
			parameters <- apply(extract(model$posterior, pars = "lambdas")$lambdas, 2, mean)
			}

	if (type == "posterior_draw") {
			if (is.null(model$posterior)) stop("Posterior distribution required")
			df <- extract(model$posterior, pars = "lambdas")$lambdas
			parameters <- df[sample(nrow(df), 2),]
			}

	model$parameters_df$parameters <- parameters
	model$parameters_df <- check_params(model$parameters_df, warning = TRUE)
	model

}


#' Get parameters
#'
#' Extracts parameters as a namesd vector
#'
#' @param model A model object generated by make_model().
#'
#' @export
#' @examples
#' get_parameters(make_model("X -> Y"))

get_parameters  <- function(model) {

	x <- model$parameters_df$parameters
  names(x) <- model$parameters_df$param_names
  x

}

