# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_type_prob_c <- function(P, parameters) {
    .Call(`_CausalQueries_get_type_prob_c`, P, parameters)
}

get_type_prob_multiple_c <- function(params, P) {
    .Call(`_CausalQueries_get_type_prob_multiple_c`, params, P)
}

realise_outcomes_c <- function(real, parents_list, endogenous_vars, n_types) {
    .Call(`_CausalQueries_realise_outcomes_c`, real, parents_list, endogenous_vars, n_types)
}

