# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' generates one draw from type probability distribution for each type in P
#'
#' @param P parameter_matrix of parameters and causal types
#' @param parameters, priors or posteriors
#' @return draw from type distribution for each type in P
get_type_prob_c <- function(P, parameters) {
    .Call(`_CausalQueries_get_type_prob_c`, P, parameters)
}

#' generates n draws from type probability distribution for each type in P
#'
#' @param params parameters, priors or posteriors
#' @param P parameter_matrix of parameters and causal types
#' @return draws from type distribution for each type in P
get_type_prob_multiple_c <- function(params, P) {
    .Call(`_CausalQueries_get_type_prob_multiple_c`, params, P)
}

#' generates realized outcomes for all causal types by sequentially calculating endogenous nodes.
#'
#' @param d a data.frame of causal types passed from within realise_outcomes
#' @param endogenous_nodes a character vector with names of endogenous nodes
#' @param parents_list a list of parents nodes for each node
#' @param nodal_types_collapsed a list of collapsed nodal types
#' @param nodal_types a list of uncolpased nodal types
#' @return a data.frame of realized outcomes for each causal type
realise_outcome_c <- function(d, endogenous_nodes, parents_list, nodal_types_collapsed, nodal_types) {
    .Call(`_CausalQueries_realise_outcome_c`, d, endogenous_nodes, parents_list, nodal_types_collapsed, nodal_types)
}

