
#' Reveal outcomes
#'
#' Reveal outcomes for all causal types. Calculated by sequentially calculating endogenous variables.
#' If a do operator is applied to any variable then it takes the given value and all its descendants are generated accordingly.
#'
#' @details \code{reveal_outcomes} starts off by creating types (via \code{\link{get_types}}). It then takes types of endogenous and reveals their outcome based on the value that their parents took. Exogenous variables outcomes correspond to their type.
#' @param model A model object generated by \code{make_model()}.
#' @param dos A named list. Do actions defining variable values, e.g., \code{list(X = 0, M = 1)}.
#' @return A data.frame object of revealed data.
#' @export
#' @examples
#' model <- make_model("X -> Y")
#' reveal_outcomes(model)
#'
#' model <- make_model("X1->Y;X2->M;M->Y")
#' reveal_outcomes(model, dos = list(X1 = 1, M = 0))
#'

reveal_outcomes <- function(model, dos = NULL){
  
  types           <- get_causal_types(model)
  nodal_types     <- get_nodal_types(model, collapse = FALSE)
  exogenous_vars  <- attr(model, "exogenous_variables")
  endogenous_vars <- attr(model, "endogenous_variables")
  types_of_exogenous         <- data.frame(types[, exogenous_vars])
  names(types_of_exogenous)  <- exogenous_vars
  types_of_endogenous        <- data.frame(types[, endogenous_vars], stringsAsFactors = FALSE)
  names(types_of_endogenous) <- endogenous_vars
  data_realizations <- types
  parents_list      <- get_parents(model)
  in_dos <- names(dos) # vars in do list
  
  # Fill in values for dos
  if(!is.null(dos))for(j in 1:length(dos)) data_realizations[, in_dos[j]] <- dos[[j]][1]
  
  
  # Work though each endogeneous variable in sequence and substitute its implied values
  for(j in 1:ncol(types_of_endogenous)) {
    if(!(endogenous_vars[j] %in% in_dos)){   # skip if do applied to var
      
      var            <- endogenous_vars[j]
      child_type     <- types_of_endogenous[,j]
      parents        <- parents_list[[var]]
      nodal_type_var <- nodal_types[[var]]
      nodal_label    <- apply(nodal_type_var, 1,paste, collapse ="")
      
      J <- sapply(1:length(child_type), function(i){
        type        <- child_type[i]
        parents_val <- data_realizations[i, parents]
        parents_val <- paste(parents_val, collapse = "")
        row         <- which(nodal_label == type )
        outcome     <- nodal_type_var[row, parents_val]
        outcome
      })
      data_realizations[, endogenous_vars[j]] <- J
    }}
  
  rownames(data_realizations) <- apply(types, 1, paste, collapse = ".")
  type_names <- matrix(sapply(1:ncol(types), function(j) paste0(names(types)[j], types[,j])), ncol = ncol(types))
  
  attr(data_realizations, "type_names") <- apply(type_names, 1, paste,  collapse = ".")
  data_realizations
  
}

