

#' Generate full dataset, possibly from compact data
#'
#' @param model A model object generated by \code{make_model()}.
#' @param n An integer. Number of observations.
#' @param data_events A compact data frame compatible with \code{model}.
#' @param parameters A numeric vector. Values of parameters may be specified. By default, parameters is drawn from priors.
#' @param using String indicating whether to use "priors", "posteriors" or "parameters". Defaults to "parameters".
#' @return A data frame of simulated data.
#' @export
#' @examples
#' model <- make_model("X -> Y")
#' data_events <- draw_data_events(model = model, n = 4)
#' simulate_data(model, data_events = data_events)

simulate_data <- function(model,
													n = 1,
													data_events = NULL,
													parameters = NULL,
													using = "parameters"){

	if(!is.null(using)) if(using == "parameters" & is.null(parameters)) {
	if(is.null(model$parameters)) stop("Using set to 'parameters' (perhaps by default) but parameters not provided. Please provide parameters or set `using` to `priors` or `posteriors`")}

	if(using == "priors" & is.null(model$priors)) {model <- set_priors(model); message("Priors missing; flat priors assumed")}

	# Data drawn here
	if(is.null(data_events)) data_events <- draw_data_events(model, n = n, parameters = parameters, using = using)

	# The rest is reshaping
	vars <- model$variables
	df <- merge(all_data_types(model), data_events, by.x = "event")
	xx  <- unlist(sapply(1:nrow(df), function(i) replicate(df[i,ncol(df)], df[i, vars])))
	out <- data.frame(matrix(xx, ncol = length(vars), byrow = TRUE))
	names(out) <- vars

	out
 }
