#' Fit causal model using 'stan'
#'
#' Takes a model and data and returns a model object with data
#' attached and a posterior model
#'
#' @inheritParams CausalQueries_internal_inherit_params
#'
#' @param data_type Either 'long' (as made by \code{\link{make_data}}) or
#'   'compact' (as made by \code{\link{collapse_data}}). Compact data must
#'   have entries for each member of each strategy family to produce a
#'   valid simplex. When long form data is provided with missingness, missing
#'   data is assumed to be missing at random.
#' @param keep_type_distribution Logical. Whether to retain
#'   \code{type_posterior}: posterior draws over causal types (draws \eqn{\times}
#'   types). Applies only on the legacy (\code{legacy = TRUE}) path; factorized
#'   updates never store \code{type_posterior}. Defaults to \code{TRUE}.
#' @param keep_event_probabilities Logical. Whether to retain posterior draws of
#'   complete-data event probabilities \code{w} (one probability per complete
#'   data pattern / column of the ambiguity matrix \code{E}). Accessible after
#'   update as \code{posterior_event_probabilities} via \code{\link{inspect}} /
#'   \code{\link{grab}}. Despite the argument name, this is \emph{not} the
#'   coarsened / observed-event vector: Stan forms that as
#'   \code{w_full = E * w} for the likelihood and does not retain
#'   \code{w_full}. Defaults to \code{FALSE}.
#' @param keep_fit Logical. Whether to keep the \code{stanfit} object produced
#'   by \link[rstan]{sampling} for further inspection.
#'   See \code{?stanfit} for more details. Defaults to `FALSE`. Note the  \code{stanfit}
#'   object has internal names for parameters (lambda), data type probabilities (w),
#'   and the type distribution (types)
#' @param censored_types vector of data types that are selected out of
#'   the data, e.g. \code{c("X0Y0")}
#' @param legacy Logical or \code{NULL}. \code{FALSE} uses the factorized /
#'   parameters-only Stan model (currently unconfounded models only).
#'   \code{TRUE} uses the causal-type Stan path. \code{NULL} (default)
#'   inherits \code{model$legacy}, then \code{options(CausalQueries.legacy)}
#'   (package default \code{FALSE}).
#' @param ... Options passed onto \link[rstan]{sampling} call. For
#'   details see \code{?rstan::sampling}
#'
#' @return An object of class \code{causal_model} with posterior distribution on
#'  parameters and other elements generated by updating; all elements accessible
#'  via \code{\link{grab}} and \code{\link{inspect}}.
#'
#' @seealso \code{\link{make_model}} to create a new model,
#'   \code{\link{summary.causal_model}} provides a summary method for
#'   output objects of class \code{causal_model}
#'
#' @references
#' Tietz T, Medina L, Syunyaev G, Humphreys M (2026).
#' "Making, Updating, and Querying Causal Models with CausalQueries."
#' \emph{Journal of Statistical Software}, \bold{117}(1), 1--40.
#' \doi{10.18637/jss.v117.i01}.
#'
#' @examples
#'  model <- make_model('X->Y')
#'  data_long   <- make_data(model, n = 4)
#'  data_short  <- collapse_data(data_long, model)
#'  model <-  update_model(model, data_long)
#'  model <-  update_model(model, data_short)
#'
#'    # It is possible to implement updating without data, in which
#'    # case the posterior is a stan object that reflects the prior
#'
#'    update_model(model)
#'
#'  \dontrun{
#'
#'    # Censored data types illustrations
#'    # Here we update less than we might because we are aware of filtered data
#'
#'    data <- data.frame(X=rep(0:1, 10), Y=rep(0:1,10))
#'    uncensored <-
#'      make_model("X->Y") |>
#'      update_model(data) |>
#'      query_model(te("X", "Y"), using = "posteriors")
#'
#'    censored <-
#'      make_model("X->Y") |>
#'      update_model(
#'        data,
#'        censored_types = c("X1Y0")) |>
#'      query_model(te("X", "Y"), using = "posteriors")
#'
#'
#'    # Censored data: We learn nothing because the data
#'    # we see is the only data we could ever see
#'    make_model("X->Y") |>
#'      update_model(
#'        data,
#'        censored_types = c("X1Y0", "X0Y0", "X0Y1")) |>
#'      query_model(te("X", "Y"), using = "posteriors")
#'  }
#'
#' @import methods
#' @import Rcpp
#' @import rstantools
#' @importFrom rstan extract
#' @importFrom rstan sampling
#'
#' @export

update_model <- function(model,
                         data = NULL,
                         data_type = NULL,
                         keep_type_distribution = TRUE,
                         keep_event_probabilities = FALSE,
                         keep_fit = FALSE,
                         censored_types = NULL,
                         legacy = NULL,
                         ...) {
  legacy <- resolve_legacy(legacy, model)
  if (!isTRUE(legacy)) {
    # Factorized Stan has no type-posterior GQ
    keep_type_distribution <- FALSE
  }

  # Guess data_type
  if (is.null(data_type)) {
    data_type <- ifelse(all(c("event", "count") %in% names(data)), "compact", "long")
  }

  # Checks on data_types
  if (data_type == "long") {
    if (is.null(data)) {
      message("No data provided")
      data_events <- minimal_event_data(model)

    } else {
      if (nrow(data) == 0 | all(is.na(data))) {
        message("No data provided")
        data_events <- minimal_event_data(model)

      } else {
        if (!any(model$nodes %in% names(data)))
          stop("Data should contain columns corresponding to model nodes")

        data_events <- collapse_data(data, model)
      }
    }
  }

  if (data_type == "compact") {
    if (!all(c("event", "count") %in% names(data))) {
      stop(paste(
        "Compact data should contain columns",
        "`event` and `count`"
      ))
    }

    if (!is.integer(data$count)) {
      count_num <- as.numeric(data$count)
      if (any(is.na(count_num) != is.na(data$count)) ||
          any(abs(count_num - round(count_num)) > 1e-9, na.rm = TRUE)) {
        warning(
          "count column should be integer valued; value has been forced to integer"
        )
      }
      data$count <- as.integer(round(count_num))
    }

    data_events <- data
  }

  if (isTRUE(legacy)) {
    stan_data <- prep_stan_data(
      model = model,
      data = data_events,
      keep_type_distribution = keep_type_distribution,
      censored_types = censored_types
    )
    stanfit <- stanmodels$simplexes
  } else {
    stan_data <- prep_stan_data_factorized(
      model = model,
      data = data_events,
      keep_event_probabilities = keep_event_probabilities,
      censored_types = censored_types
    )
    stanfit <- stanmodels$simplexes_factorized
    if (is.null(stanfit)) {
      stanfit <- get_stanmodel_factorized()
    }
  }

  # parameters to drop (match Stan: we no longer materialize w_full or intermediate computation objects)
  drop_pars <- c("gamma", "sum_gammas", "log_sum_gammas", "w_full", "w_0")

  if (!keep_event_probabilities) {
    drop_pars <- c(drop_pars, "w")
  }

  if (isTRUE(legacy) && !keep_type_distribution) {
    drop_pars <- c(drop_pars, "types")
  }


  sampling_args <- set_sampling_args(
    object = stanfit,
    user_dots = list(...),
    data = stan_data,
    pars = drop_pars,
    include = FALSE
  )

  newfit <- do.call(rstan::sampling, sampling_args) |> capture_warnings()

  model$stan_objects  <- list(data = stan_data$data, stan_warnings = newfit$warnings)


  # Keep full fit object
  if (keep_fit) {
    model$stan_objects$stanfit <- newfit$fit
  }

  # Retain posterior distribution
  model$posterior_distribution <-
    extract(newfit$fit, pars = "lambdas")$lambdas |>
    as.data.frame()
  colnames(model$posterior_distribution) <- get_parameter_names(model)

  # Retain type distribution (legacy only)
  if (isTRUE(legacy) && keep_type_distribution) {
    model$stan_objects$type_posterior <- extract(newfit$fit, pars = "types")$types

    colnames(model$stan_objects$type_posterior) <- colnames(stan_data$P)
  }

  # Retain data type probabilities (w); columns of E are data types, so
  # colnames(stan_data$E) labels w. Stan's event-level object is w_full = E * w.
  if (keep_event_probabilities) {
    model$stan_objects$event_probabilities <- extract(newfit$fit, pars = "w")$w
    colnames(model$stan_objects$event_probabilities) <- colnames(stan_data$E)
  }

  # Retain stanfit summary with readable names (lambdas + lp__ by default;
  # include w / types only when those objects are kept)
  params <- colnames(model$posterior_distribution)
  print_pars <- "lambdas"
  if (keep_event_probabilities) {
    params <- c(params,
                colnames(model$stan_objects$event_probabilities))
    print_pars <- c(print_pars, "w")
  }

  if (isTRUE(legacy) && keep_type_distribution) {
    params <- c(params, colnames(model$stan_objects$type_posterior))
    print_pars <- c(print_pars, "types")
  }

  params <- c(params, "lp__")
  print_pars <- c(print_pars, "lp__")

  model$stan_objects$stan_summary <- utils::capture.output(
    print(newfit$fit, pars = print_pars)
  )

  params_labels <- newfit$fit@sim$fnames_oi
  # Only rename labels that appear in the printed subset
  keep_lab <- grepl(
    paste0("^(", paste(print_pars, collapse = "|"), ")(\\[|$)"),
    params_labels
  )
  params_labels <- params_labels[keep_lab]
  n_replace <- min(length(params), length(params_labels))
  if (n_replace > 0L) {
    width <- max(nchar(c(params[seq_len(n_replace)],
                         params_labels[seq_len(n_replace)])))
    pad <- function(x) paste0(x, strrep(" ", width - nchar(x)))
    padded_params <- pad(params[seq_len(n_replace)])
    padded_labels <- pad(params_labels[seq_len(n_replace)])
    for (i in seq_len(n_replace)) {
      model$stan_objects$stan_summary <-
        gsub(
          pattern = padded_labels[i],
          replacement = padded_params[i],
          x = model$stan_objects$stan_summary,
          fixed = TRUE
        )
    }
  }

  # So query_* / later steps inherit the method used for this posterior
  model <- stamp_legacy(model, legacy)
  model <- clear_model_cache(model)

  return(model)
}


capture_warnings <- function(expr) {
  # Initialize a variable to store captured warnings
  warnings_captured <- character()

  # Capture warnings and the result (muffle so callers / tests do not
  # also see Stan ESS and similar sampling noise).
  fit <- withCallingHandlers(
    expr,
    warning = function(w) {
      warnings_captured <<- c(warnings_captured, conditionMessage(w))
      tryInvokeRestart("muffleWarning")
    }
  )

  # List containing the result of the expression and the warnings
  list(fit = fit, warnings = warnings_captured |> concise())
}


concise <- function(warnings) {
  # Apply transformations based on the patterns
  sapply(warnings, function(warning) {
    if (grepl("not mixed", warning)) {
      sub("not mixed.*", "not mixed", warning)  # Truncate after "not mixed"
    } else if (grepl("too low", warning)) {
      sub("too low.*", "too low", warning)  # Truncate after "too low"
    } else {
      warning  # Leave the warning unchanged if no match
    }
  }, USE.NAMES = FALSE) |>
    paste(collapse = "\n")# Ensure it returns a vector
}
